version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/app/data
      - /home/daknoblo/stacks:/home/daknoblo/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/daknoblo/stacks/
